### ISSUE TITLE
casacore is too old?

### ISSUE THREAD

**Issue by amisk** [casacore/python-casacore#108]
Hi!

I am trying to install the latest python-casacore version.
I just installed casacore itself by using svn and specifying 2.3.0.
But when I try to install python-casacore, it kees saying that my casacore version is older than 2.3 and incompatible ...

Any ideas? :)

**Comment by shibasisp** [comment]
Hii!
strange..Could you please do a clean install of both casacore and python-casacore once again and check?

**Comment by tammojan** [comment]
Could you check that you really have casacore 2.3.0 by typing `taql --version`?

**Comment by amisk** [comment]
Hi,

if I type taql --version, I get the error that --version is an invalid option.

**Comment by tammojan** [comment]
That means you do not have casacore 2.3.0 (this feature was introduced in version 2.2.0, see https://github.com/casacore/casacore/commit/fb5925c67b762f8bc022347b4aa1e2f15f4f73a2 )

**Comment by amisk** [comment]
Ok ... but how can that be? I got the source through:

svn co https://github.com/casacore/casacore/tags/v2.3.0 source

**Comment by tammojan** [comment]
Perhaps an old installation which takes precedence? Does `which taql` show you the right path?

**Comment by amisk** [comment]
yes, it shows me the path to a binary that was created two weeks ago.

**Comment by amisk** [comment]
Ok, I have no idea why, but this time it appears to work .... the setup.py of python-casacore is no longer complaining about casacore. Now it complains about missing fitsio.h, but thats a different topic and I will try to solve this before I open up another issue :)

Thank you!

**Comment by amisk** [comment]
Hello,

Sorry to open this up again, but I am installing the software on another machine, and I have the same problem again. But this time taql --version actually shows 2.3.0,  but python-casacore says that my version is older than that.

This is what I've done:

Casacore2 installation:

cd /opt/soft/lofar-stuff/BuildDir
wget https://github.com/casacore/casacore/archive/v2.3.0.tar.gz
tar -xvf v2.3.0.tar.gz
cd casacore-2.3.0/
mkdir -p build/opt
cd build/opt
cmake -DBUILD_TESTING=NO -DCMAKE_INSTALL_PREFIX=/opt/soft/lofar-stuff -DUSE_FFTW3=Yes -DUSE_THREADS=YES -DWCSLIB_ROOT_DIR=/opt/soft/lofar-stuff -DBUILD_PYTHON=True -DDATA_DIR=/opt/soft/lofar-stuff/data ../..
make -j
make install

python-casacore installation:

cd /opt/soft/lofar-stuff/BuildDir/
git clone https://github.com/casacore/python-casacore.git
cd python-casacore
export PATH=$PATH:/opt/soft/lofar-stuff/bin
export LD_LIBRARY_PATH=/opt/soft/lofar-stuff/lib
export PYTHONPATH=/opt/soft/lofar-stuff/lib/python2.7/site-packages/
ln -s /opt/soft/lofar-stuff/lib /opt/soft/lofar-stuff/lib64
mkdir -p /opt/soft/lofar-stuff/lib/python2.7/site-packages/
./setup.py build_ext -I/opt/soft/lofar-stuff/include -L/opt/soft/lofar-stuff/lib
./setup.py install --prefix=/opt/soft/lofar-stuff
