### ISSUE TITLE
pyrap.tables.addImagingColumns() not compatible with lwimager

### ISSUE THREAD

**Issue by o-smirnov** [casacore/python-casacore#11]
See https://github.com/ska-sa/lwimager/issues/3.

Underlying issue seems to be that lwimager seems to want a CHANNEL_SELECTION keyword in MODEL_DATA of the form ```{'CHANNEL_SELECTION': array([[ 0, 32]], dtype=int32)}```, while addImagingColumns() adds something that omits the dtype attribute.

Workaround is to add these via lwimager. Remove the CHANNEL_SELECTION keyword using pyrap.tables, then

```
lwimager ms=foo.MS/ operation=empty fillmodel=1
```

**Comment by tammojan** [comment]
Indeed the dtype is missing in some revisions of pyrap (I've seen it in release 0.3 , which I cannot find anywhere but on a user's computer).

However, in the current python-casacore the dtype is added in `msutil.py`:
```
t.putcolkeyword ('MODEL_DATA', 'CHANNEL_SELECTION', np.int32(chans))
```

**Comment by tammojan** [comment]
Double checked this, it was fixed in the pyrap trunk after the latest (last?) pyrap release. Closing it here as invalid.
