### ISSUE TITLE
Refer to subtable in taql with variable expansion

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#116]
I would like to refer to a subtable from python. I have the following
```
import casacore.tables as pt
ms="L123.MS"
pt.taql("SELECT FROM $ms") # works
```
Now I would like to refer to the `ANTENNA` subtable of the measurement set using the variable `ms`. Neither of the following work:
```
pt.taql("SELECT * FROM $ms::ANTENNA")
RuntimeError: Error in TaQL command: using style Python SELECT * FROM "L123.MS"::ANTENNA
  parse error at or near position 104 '::ANTENNA'

pt.taql("SELECT * FROM $ms/ANTENNA")
RuntimeError: Error in TaQL command: using style Python SELECT * FROM "L123.MS"/ANTENNA
  parse error at or near position 103 '/ANTENNA'
```

Am I missing an obvious way to achieve this, or should the code that expands variables be expanded?

**Comment by gervandiepen** [comment]
The issue can be circumvented by enclosing the subtable in quotes such as:
     $ms'::ANTENNA'
However, it is somewhat cumbersome, so I'll change Casacore such that it will accept
    "L123.MS"::ANTENNA
python-casacore does not need to be changed.

**Comment by gervandiepen** [comment]
This seems to work fine. Probably it has been fixed some time ago.
Please check and close the ticket.
