### ISSUE TITLE
"Could not find a boost library" with boost 1.53 on CentOS 7.2

### ISSUE THREAD

**Issue by alxames** [casacore/python-casacore#118]
Just did a git pull, then ran:
```
./setup.py build_ext -I/opt/casacore-2.3.0/include -L/opt/casacore-2.3.0/lib
```
and got:
```
Traceback (most recent call last):
  File "./setup.py", line 65, in <module>
    raise Exception("Could not find a boost library")
Exception: Could not find a boost library
```
Last time I installed python-casacore, this wasn't a problem. We didn't update boost.
The problem persists after removing already built/configured outputs (clean source dir).

**Comment by tammojan** [comment]
It should work with:
```
./setup.py build_ext -I/opt/casacore-2.3.0/include -L/opt/casacore-2.3.0/lib:/lib64
```

**Comment by alxames** [comment]
Yes, this works. Thanks.
I do hope that python-casacore can, at some point again, detect boost in the standard lib or lib64 path(s) automatically. But I'll close this for now.

**Comment by alxames** [comment]
Install trips over the same error. The -L option works for boost, but not to find libcasa_casa.so. I don't get this and no longer have time to dive in. Any idea?
```
$ ./setup.py install --prefix=/opt/casacore-2.3.0 
Traceback (most recent call last):
  File "./setup.py", line 65, in <module>
    raise Exception("Could not find a boost library")
Exception: Could not find a boost library
```
```
$ ./setup.py install --prefix=/opt/casacore-2.3.0 -L/lib64
Traceback (most recent call last):
  File "./setup.py", line 117, in <module>
    raise Exception("Could not find libcasa_casa.so")
Exception: Could not find libcasa_casa.so
```
```
$ ./setup.py install --prefix=/opt/casacore-2.3.0 -L/opt/casacore-2.3.0/lib -L/lib64
Traceback (most recent call last):
  File "./setup.py", line 117, in <module>
    raise Exception("Could not find libcasa_casa.so")
Exception: Could not find libcasa_casa.so
```
```
$ ./setup.py install --prefix=/opt/casacore-2.3.0 -L/opt/casacore-2.3.0/lib:/lib64
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option -L not recognized
```

Even this fails (instructed just above):
```
$ ./setup.py install --help    # or ./setup.py cmd --help
Traceback (most recent call last):
  File "./setup.py", line 65, in <module>
    raise Exception("Could not find a boost library")
Exception: Could not find a boost library
```

**Comment by tammojan** [comment]
I agree the current code is not pretty. A quick way to make it work is to put the paths in the `setup.py` itself instead of specifying it on the command line.

**Comment by gijzelaerr** [comment]
you should first build the library using `build_ext` and -L flags, then install them. You can't use -L flags during install.

**Comment by gijzelaerr** [comment]
I've made the setup.py a bit less grumpy, it should not raise exceptions, just warn the user. The compiler will fail if something is wrong.

https://github.com/casacore/python-casacore/commit/690cbfe7f0e021398ed7afc1e110c0ab37ece5a6

**Comment by gijzelaerr** [comment]
I assume this is not an issue anymore now.
