### ISSUE TITLE
[2.2] setup.py fails on non-x64_64 Debian machines

### ISSUE THREAD

**Issue by olebole** [casacore/python-casacore#123]
`setup.py` uses a hand-made function `find_library_file()` to check for boost and libcasacasa. This function has the disadvantage that architecture dependent paths are coded in; namely `/usr/lib/x86_64-linux-gnu`. This does not work for any other architecture -- arm, arm64, i386 etc, and consequently the build on those architectures [fails](https://buildd.debian.org/status/logs.php?pkg=python-casacore&ver=2.2.0-1).

That is a regression, on 2.12 [the builds were fine](https://buildd.debian.org/status/logs.php?pkg=python-casacore&ver=2.1.2-5).

**Comment by tammojan** [comment]
Thanks @olebole. The idea of this function is to check the library file for its version number. Do you have an idea how to do this more properly?

**Comment by olebole** [comment]
Not in the moment; what was the reason to change this between 2.1.2 and 2.2?
I however see that the failure may be fixed with d8e1f94cd00f42408a460fdc294f926778fcbaff (which however indicates that the current solution may be not very robust).

**Comment by tammojan** [comment]
The reason for the change is that python-casacore now depends on casacore 2.3.0.

**Comment by olebole** [comment]
Update here: d8e1f94 seems not to help -- one then gets a failure because somewhere `None` is added to the libs instead of libboost.
What pragmatically helps is to return the default `boostlibnames[0]` instead of `None` in the not-found branch of `find_boost()` -- since the name ist known on Debian.

> The reason for the change is that python-casacore now depends on casacore 2.3.0.

That is just a warning. The problem is that the Python boostlib is set to `None`, where `setup()` later stumbles upon.

**Comment by tammojan** [comment]
I think this should be resolved on the current master.
