### ISSUE TITLE
Feature request: support writing unicode strings

### ISSUE THREAD

**Issue by bmerry** [casacore/python-casacore#138]
When using putcol to write a numpy array of unicode strings (e.g. dtype 'U11') it fails with an error `PycArray: unknown python array data type`. In Python 3 these arrays arise from e.g. `np.array(['hello'])` because Python 3 strings are Unicode.

It would be nice if these arrays could be automatically encoded. I don't know enough about what encodings are assumed by other MS tools, but presumably UTF-8 would be a sane choice for character encoding.

**Comment by gijzelaerr** [comment]
unfortunately, this is still an issue, even after the merge of the unicode improvements.

**Comment by gijzelaerr** [comment]
should be implemented with https://github.com/casacore/python-casacore/pull/168

**Comment by gijzelaerr** [comment]
this should be solved.
