### ISSUE TITLE
mock the compiled modules so the doc generation of readthedocs works

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/python-casacore#14]
at the moment we auto generate the doc on readthe docs:

http://python-casacore.readthedocs.org/

Problem is that some autodoc logic does not work, since it requires the compiled python-casacore modules installed, something impossible to do on readthedocs. We can solve this by mocking the boost modules, but this is less straight forward than I was hoping.

**Comment by sjperkins** [comment]
Perhaps @shibasisp might like to have a go at this?

I recently did something similar for Montblanc. Here is the relevant [commit range](https://github.com/ska-sa/montblanc/commits/rime-tf?author=sjperkins&since=2017-04-05T22:00:00Z&until=2017-04-07T22:00:00Z)

**Comment by shibasisp** [comment]
Hey @sjperkins ! I would love to go with this! Thanks for the commit range for reference.

**Comment by tammojan** [comment]
Actually this is not necessary anymore for producing the docs, since that is now done by travis. See #80.

**Comment by gijzelaerr** [comment]
ok, then i'll close this issue.
