### ISSUE TITLE
"Expecting an object of type dict; got an object of type dict instead"

### ISSUE THREAD

**Issue by pkgw** [casacore/python-casacore#144]
I'm currently experiencing a resurrection of a problem that seems to have cropped up before:

- [pyrap #20](https://code.google.com/archive/p/pyrap/issues/20)
- [GitHub #15](https://github.com/casacore/python-casacore/issues/15)

The problem is a befuddling error message on macOS:

```python
    tb_spws = tables.table(filepath + '/SPECTRAL_WINDOW')
  File "/Users/travis/miniconda3/conda-bld/pyuvdata_1541378310775/_test_env_.../lib/python3.6/site-packages/casacore/tables/table.py", line 375, in __init__
    Table.__init__(self, tabname, lockopt, opt)
TypeError: Expecting an object of type dict; got an object of type dict instead
```

(from [this log](https://travis-ci.org/conda-forge/pyuvdata-feedstock/jobs/450649747#L680-L683) associated with [this PR](https://github.com/conda-forge/pyuvdata-feedstock/pull/7) to a package that uses python-casacore).

The consensus seems to have been that this is what happens when you accidentally mix versions of the Boost or Python libraries in different elements of the casacore stack: one piece of the code has a different idea of what constitutes "a dict" than another, since they managed to get linked with different versions of `libpython` somehow.

But the weird thing here is that these packages are built in the conda-forge framework, which involves reproducible environments, and as best I can tell, everything was compiled with self-consistent dependencies. Even weirder, the problem only manifests in Python 3.x on macOS when built with recent Clang++; it doesn't show up for the older set of compilers that conda-forge used to use.

I'm at a loss as to how to debug this. Does anyone here have any suggestions? I've examined the build logs and the linkages of the relevant libraries carefully but can't spot anything suspicious, and I'm not sure what else to try. (Annoyingly, conda-forge doesn't have anything like a "debuginfo" package, so I don't know of a way to open things up in gdb and really investigate the guys of what's going on.)

**Edit**: For reference

- [Travis logs of deployed casacore builds](https://travis-ci.org/conda-forge/casacore-feedstock/builds/450603781)
- [Travis logs of deployed python-casacore builds](https://travis-ci.org/conda-forge/python-casacore-feedstock/builds/450639050)
- [Travis logs of deployed Boost builds](https://travis-ci.org/conda-forge/boost-feedstock/builds/441085847)
- [Circle CI logs of deployed Python builds](https://circleci.com/gh/conda-forge/python-feedstock/626), I think — this was built in a somewhat nonstandard way

**Comment by gervandiepen** [comment]
Indeed very strange.
The only thing I can think of is that you look carefully at PYTHONPATH and
especially (DY)LD_LIBRARY_PATH and check if they are not different from the
paths used during the build.

**Comment by pkgw** [comment]
I doubt that's it, since the conda system is good about not needing to set such environment variables.

At the moment I'm trying to see if I can boil it all down to a minimal test case, but it's going to be slow going.

**Comment by tammojan** [comment]
Python-casacore looks for the 'right' boost-python library by its name. The name for boost python differs between distributions, also between for example homebrew and conda.

A way to debug this is to use `otool -L _tables.dylib` and make sure it point to the right boost-python and python libraries. Same for `libcasa_tables.dylib`.

If it all looks ok (and it's not), it may be useful to run the following test:
```
DYLD_PRINT_LIBRARIES=1 python -c 'import casacore.tables as pt; t=pt.table("~/small.MS")'
```
Grep the output on boost_python and python.

**Comment by gijzelaerr** [comment]
I've experienced the same issues when mixing up the compile time and runtime shared libraries.

**Comment by gijzelaerr** [comment]
I think in the end this is a user error, and we can't do much about it apart from making it harder for a user to shoot herself in the foot. Opening a new issue for that: https://github.com/casacore/python-casacore/issues/145

**Comment by pkgw** [comment]
@gijzelaerr I definitely agree that this isn't really casacore's fault in a lot of ways. There might be ways to add build configuration checks to prevent certain common broken scenarios, I suppose?

*Once I iron out this problem*, I'd say that distribution through conda-forge is your best bet to having the reliable installation as mentioned in #145 — this is exactly the sort of thing that Conda packages are supposed to help with! And thus far the packages have worked out pretty well. I still need to work out what's going on in this particular case, but it's worth emphasizing that of the 2 (OS's) × 3 (supported Python versions) × 2 (compiler toolchains) elements of the configuration matrix, only one has a problem.

**Comment by pkgw** [comment]
After further investigation ... I think I have isolated the general class of issue, and this might actually be a bug in python-casacore! But it gets much beyond my C++-fu so I'm not sure if it's anything you can do something about.

When using the new conda-forge compiler on macOS, there seems to be some problem involving coherency between templates instantiated inside `libcasa_python3.dylib` and extension modules like `_tables.so` ... or something. Because the code works fine on many platforms, this is probably a toolchain bug, but I'm hoping that maybe you have an idea of how to avoid it (besides the hack I show below).

Below is the minimal test case I can devise. The basic structure is as follows: there is a dynamic library `libmylib.dylib`. There is a Python extension module, `myext.so`, that links to this library. Depending on what symbols are defined in the module, sometimes code in the library has different values for certain Python symbols that causes the "expected dict not dict" bug.

Here is `mylib.cpp`, the source of the dynamic library:

```c++
#include <boost/python.hpp>
#include <boost/python/dict.hpp>
#include <iostream>

using namespace boost::python;

void in_the_library(PyObject *obj)
{
    std::cout << "  PyDict_Check(): " << PyDict_Check(obj) << std::endl << std::flush;
    std::cout << "Our &PyDict_Type: " << &PyDict_Type << std::endl << std::flush;
    std::cout << "        Its type: " << obj->ob_type << std::endl << std::flush;
    dict d = extract<dict>(obj)(); // <= exception potentially raised here
}
```

Here is `myext.cpp`, the extension module:

```c++
#include <boost/python.hpp>
#include <boost/python/dict.hpp>
#include <iostream>

using namespace boost::python;

extern void in_the_library(PyObject *obj);

int call_the_lib(PyObject *obj)
{
    in_the_library(obj);
    return 0;
}

int totally_random_function(PyObject *obj)
{
    // If "#if 1" is used here, there is no crash. If "#if 0" is used, there is.
#if 0
    dict d = extract<dict>(obj)();
#endif
    return 0;
}

BOOST_PYTHON_MODULE(myext)
{
    def("call_the_lib", call_the_lib);
}
```

Here is `bug.py`, which calls the module and makes the outcome clear:

```python
#! /usr/bin/env python

import myext

try:
    myext.call_the_lib({})
except TypeError as e:
    print()
    print('****BUG***', e)
else:
    print()
    print('No bug.')
```

Finally, here is a Makefile that can build everything, assuming a Conda environment using the new "gcc7" packages of Boost from conda-forge, as well as the availability of the relevant compiler:

```
PWD = $(shell pwd)
CONDA = /Users/peter/miniconda3
CC = x86_64-apple-darwin13.4.0-clang++

CPPFLAGS = -I$(CONDA)/include -I$(CONDA)/include/python3.6m

EXTFLAGS = -bundle -undefined dynamic_lookup \
  -Wl,-rpath,$(CONDA)/lib -L$(CONDA)/lib \
  -Wl,-rpath,$(PWD) -L$(PWD)

myext.cpython-36m-darwin.so: myext.cpp libmylib.dylib Makefile
	$(CC) $(CPPFLAGS) $(EXTFLAGS) -g -Wall -O0 -o $@ $< -lmylib

LIBFLAGS = -dynamiclib -Wl,-rpath,$(CONDA)/lib -L$(CONDA)/lib

libmylib.dylib: mylib.cpp Makefile
	$(CC) $(CPPFLAGS) $(LIBFLAGS) -g -Wall -O0 -o $@ $< -lboost_python36 -lpython3.6m
```

If I build using `#if 1` in `myext.cpp`, I get output like:

```
  PyDict_Check(): 1
Our &PyDict_Type: 0x10bbe9c80
        Its type: 0x10bbe9c80

No bug.
```

If I build using `#if 0`, I get:

```
  PyDict_Check(): 1
Our &PyDict_Type: 0x10eb8f2a0
        Its type: 0x10e433c80

****BUG*** Expecting an object of type dict; got an object of type dict instead
```

My best interpretation is that activating the key line causes a reference to the `boost::python::extract` template (and related symbols) to be created in the library, which somehow makes sure that when the binary is loaded all of the Python symbols (such as `PyDict_Type`) are coherent between the main process, the extension, and the dylib. Without such a reference, somehow the dylib seems to get a different `libpython` image, leading to a different address for `PyDict_Type`, which causes the Boost type check to fail given the way that it's implemented.

Another way for me to avoid the bug is to compile `libmylib.dylib` without linking to `libpython`, passing `-undefined dynamic_lookup` on its link line as well. Then I get no bug regardless of the `#if` statement.

Sorry, I know that's all very dense. The bottom line is: if you can suss out the issue here, do you happen to know of some compiler or linker flag that might prevent the problem? I don't know anything about linking C++ templates besides "it's very complex".

Also: if you're interested in reproducing this yourselves, I can give more detailed instructions for setting up the necessary environment.

**Comment by k-dominik** [comment]
Thanks a lot for opening this issue and documenting progress and solution. This really helped me!

**Comment by ludwigschwardt** [comment]
Hi @pkgw, you answered your own question... 😄

> The bottom line is: if you can suss out the issue here, do you happen to know of some compiler or linker flag that might prevent the problem?

> Another way for me to avoid the bug is to compile `libmylib.dylib` without linking to `libpython`, passing `-undefined dynamic_lookup` on its link line as well. Then I get no bug regardless of the `#if` statement.

*Never* link against `libpython` and *always* use `-undefined dynamic_lookup`. This [post](https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/) explains it very well.

I just [enforced](https://github.com/ska-sa/homebrew-tap/pull/19/commits/b2fad8fd6ac0f519d477a5cf23c61ca9a4ce657a) this last month in my Homebrew formula.

**Comment by pkgw** [comment]
OK, I got this working on conda-forge and I don't see a clear action item for python-casacore here, so I'll close this.
