### ISSUE TITLE
how to enable c++11?

### ISSUE THREAD

**Issue by amisk** [casacore/python-casacore#150]
Hi,

I am trying to install the latest software for lofar. If I install the latest casacore, I cannot compile python-casacore, it says:
`/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
`
I can't find an option to specify this. The setup.py file does not take this.

How I can compile that?
Thx.

**Comment by gervandiepen** [comment]
Do
  export CFLAGS='-std=c++11'
before
  python setup.py build_ext ....

**Comment by amisk** [comment]
Thank you. Appears to be working.

**Comment by gervandiepen** [comment]
Casarest needed some changes to build with the new casacore.
I've created a PR for that, so you have to wait until it is merged. It will
use c++11.
