### ISSUE TITLE
Creation of masked image

### ISSUE THREAD

**Issue by DavidGMcConnell** [casacore/python-casacore#151]
I found the following behaviour unexpected, and it seems illogical.

According to the documentation for casacore.images.image
> ‘values`
If given, the image will be created and these values will be stored in it. It should be a numpy array or masked array. If it is a masked array, its mask acts as the mask argument described below. The data type of the image is derived from the array’s data type.

And 'below': 
> The data should be a numpy array. Its dimensionality must be the same as the dimensionality of the image. Note that the casacore images use the convention that a mask value True means good and False means bad. However, numpy uses the opposite. Therefore the mask will be negated, so a numoy masked can be given directly.

The following works:
`    im_new = cim.image(name, coordsys=co_new)`
`    im_new.put(ys)`
where
type(ys) : <class 'numpy.ma.core.MaskedArray'>
ys.shape : (88, 88)

However,  
`    im_new = cim.image(name, values=ys, coordsys=co_new)`

results in:
>    im_new = cim.image(name, values=ys, coordsys=co_new)
  File "/Users/mcc381/miniconda2/envs/aces/lib/python2.7/site-packages/casacore/images/image.py", line 172, in __init__
    mask = -mask  # casa and numpy have opposite flags
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

**Comment by gervandiepen** [comment]
It has been fixed by PR#179.

**Comment by DavidGMcConnell** [comment]
Very good. Thank you.
David McConnell
ASKAP Commissioning & Early Science Manager
CASS, CSIRO
david.mcconnell@csiro.au
+61 2 9372 4132
