### ISSUE TITLE
 tConvert ValueHolder overflow error

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/python-casacore#169]
@bmerry writes:

Regarding the tConvert ValueHolder overflow error: my guess is that you should adapt the behaviour to the value of the integer, rather than the Python type. So for example, first try to extract as 'int', and if that fails, fall back to extract as Int64.

**Comment by gervandiepen** [comment]
The #ifdef on IS_PY3K in PycValueHolder.cc is not correct. It should not do the PyLong_Check instead of the PyInt_Check because that test is done right after it.
So it should get #ifndef IS_PY3K at line 101, 159 and 251 without the PyLong and #else part.

**Comment by gijzelaerr** [comment]
i don't understand what you try to say. python3 only has a long type for int?

**Comment by gervandiepen** [comment]
Basically you handle a Python long as a C++ int for Python3 because of the
PyLong test in the #ifdef. Instead always handle PyLong as Int64 for both
Python2 and 3.
I can make the change tomorrow if you like to.

**Comment by gijzelaerr** [comment]
ok please do, I'm out of time to work on this now.

**Comment by gijzelaerr** [comment]
This should be resolved.
