### ISSUE TITLE
quanta example not working with python 2.7.6

### ISSUE THREAD

**Issue by twillis449** [casacore/python-casacore#17]
from the example at http://python-casacore.readthedocs.org/en/latest/casacore_quanta.html

from casacore import quanta
boltzmann = quanta.constants['k']
print 'the next line fails with python 2.7.6'
print 'Boltzmann constant is ', boltzmann
print 'the next line seems to work'
print ('Boltzmann constant is ', boltzmann)

gives

the next line fails with python 2.7.6
Boltzmann constant is  0.00000 J/K
the next line seems to work
('Boltzmann constant is ', 1.38066e-23 J/K)

**Comment by twillis449** [comment]
Interestingly, the same errors occur if pyrap is used.

**Comment by tammojan** [comment]
I can confirm this with Python 2.7.3.

**Comment by gijzelaerr** [comment]
This is caused by a difference in the implementation of str and representation of the object:

```
In [9]: boltzmann.__repr__()
Out[9]: '1.38066e-23 J/K'

In [10]: boltzmann.__str__()
Out[10]: '0.00000 J/K'
```

**Comment by tammojan** [comment]
Should this be fixed?

**Comment by gijzelaerr** [comment]
it should, not sure how yet, not familiar with boost python.

I think it has something to do with this:
https://github.com/casacore/python-casacore/blob/master/casacore/quanta/quantity.py#L31

**Comment by gervandiepen** [comment]
It has to do with function to_string which uses an incorrect format for such a small value.
   '%0.5f' % 1e-23
also gives 0.000
Either the default format of to_string should be changed to %0.5g or __str__ should be outcommented.
I think I prefer the first option. What do you think?

**Comment by gijzelaerr** [comment]
I trust your judgement!
