### ISSUE TITLE
python3 and measures.get_value seems to have a problem with indexing keys()

### ISSUE THREAD

**Issue by tmolteno** [casacore/python-casacore#186]
This appears to be a python3 issue:

Steps to reproduce:

    from casacore.measures import measures

    dm = measures()
    epoch = dm.epoch(rf='utc', v0=ts.isoformat())
    epoch_d = dm.get_value(epoch)

Produces the following error:

    File "XXXXX.py", line 132, in timestamp_to_ms_epoch
        epoch_d = dm.get_value(epoch)
     File "/usr/lib/python3/dist-packages/casacore/measures/__init__.py", line 629, in getvalue
        keys = v.keys()[:]
    TypeError: 'dict_keys' object is not subscriptable

In Python 3 dict.keys() returns an iterable but not indexable object.

        keys = list[v.keys()]

should do the trick.

**Comment by tammojan** [comment]
Thanks for reporting, and providing the fix! This should be fixed in #187
