### ISSUE TITLE
Travis does not test python2 anymore

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#188]
The python-casacore travis jobs (e.g. https://travis-ci.org/casacore/python-casacore/jobs/612360169) now run python3 by default. To test python2.7, it should be possible to set `python=2.7` somewhere in `.travis.yml`, but I don't know how to get this into the build matrix.

**Comment by gijzelaerr** [comment]
the docker containers test python2 right?

**Comment by tammojan** [comment]
Yes that's right.
