### ISSUE TITLE
LOFARsofts Dockerfile crashes at python-casacore

### ISSUE THREAD

**Issue by AlexKurek** [casacore/python-casacore#199]
Im getting this error while trying to compile:
https://git.astron.nl/ro/lofar/-/blob/master/Docker/lofar-base/Dockerfile.tmpl
CPU on this machine: Xeon(R) CPU E5-2640 v2

> Cloning into 'python-casacore'...
> Note: checking out '3342e15af1e00560e9d1b13d5686a1f6aaef04a4'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
> git checkout -b
> 
> /bin/bash: line 1: 974 Illegal instruction (core dumped) python3 ./setup.py build_ext -I${INSTALLDIR}/casacore/include/ -L${INSTALLDIR}/casacore/lib/
> The command '/bin/bash -c export BUILD_PACKAGES="git make g++ python3-setuptools libboost-python${BOOST_VERSION}-dev libcfitsio-dev wcslib-dev" && aptitude install -y ${BUILD_PACKAGES} && mkdir ${INSTALLDIR}/python-casacore && cd ${INSTALLDIR}/python-casacore && git clone --depth 1 --shallow-submodules --branch ${PYTHON_CASACORE_VERSION//latest/master} https://github.com/casacore/python-casacore.git && cd ${INSTALLDIR}/python-casacore/python-casacore && python3 ./setup.py build_ext -I${INSTALLDIR}/casacore/include/ -L${INSTALLDIR}/casacore/lib/ && mkdir -p ${INSTALLDIR}/python-casacore/lib/python${PYTHON_VERSION}/site-packages/ && mkdir -p ${INSTALLDIR}/python-casacore/lib64/python${PYTHON_VERSION}/site-packages/ && export PYTHONPATH=${INSTALLDIR}/python-casacore/lib/python${PYTHON_VERSION}/site-packages:${INSTALLDIR}/python-casacore/lib64/python${PYTHON_VERSION}/site-packages:${PYTHONPATH} && cd ${INSTALLDIR}/python-casacore/python-casacore && python3 ./setup.py install --prefix=${INSTALLDIR}/python-casacore/ && bash -c "rm -rf ${INSTALLDIR}/python-casacore/python-casacore" && aptitude purge -y ${BUILD_PACKAGES} && aptitude clean && aptitude autoclean' returned a non-zero code: 132

**Comment by AlexKurek** [comment]
Solved by changing:
https://git.astron.nl/ro/lofar/-/blob/master/Docker/lofar-base/Dockerfile.tmpl#L65
to `-march=native`

**Comment by tammojan** [comment]
Great. Have you committed that to the LOFAR repo, or made a PR?

**Comment by AlexKurek** [comment]
No really, Im not a member of this project and Im not a programmer, Im not sure if I can do that

**Comment by tammojan** [comment]
Ok, I'll see if I can do that.

**Comment by tammojan** [comment]
Closed because not really a python-casacore problem.

**Comment by tjuerges** [comment]
Just for completeness:
There is a bug in the Dockerfile for lofar-base.  LOFAR_BUILDVARIANT can be set but it's setting not always observed.  I will fix this later today.

**Comment by AlexKurek** [comment]
On Xeon(R) CPU E5-2640 v2 when I compile lofar-base + lofar-pipeline and try tu run Prefactor 3, it crashes immediately giving 

> illegal instruction (core duped).

Same thing is working on Xeon(R) Gold 5115. Maybe this is the reason

**Comment by tjuerges** [comment]
Hi Alex,
the latest tagged release (LOFAR-Release-4_0_16) should have a fix for the issue.  Please set the Docker --build-arg CPU_OPTIMISATION="x86-64" and LOFAR_BUILDVARIANT="gnucxx11_opt". This will build everything for Intel 64-bit CPUs without any CPU speficic optimisations.  Once you have verified that the image works, you can begin building the images on the system where you intend to later execute them. This will allow you to specify LOFAR_BUILDVARIANT="gnucxx11_optarch" and CPU_OPTIMISATION="native".  These settings will then tell the compilers to generate the most performant assembler code for the CPU type that is compiling the code.

**Comment by AlexKurek** [comment]
Hi,
I will compile it and see if its working on my machine. Meanwhile I noticed:
`getcwd() failed: No such file or directory`
I will not break the compilation in case of apt-get (in case of pip it would!), but if you want to get rid of it, before this line:
https://git.astron.nl/ro/lofar/-/blob/master/Docker/lofar-base/Dockerfile.tmpl#L114
add `cd ../..`
The same for casarest

**Comment by AlexKurek** [comment]
I compilled using `LOFAR_BUILDVARIANT="gnucxx11_optarch"` and `CPU_OPTIMISATION="native"` and I got:

> log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
> log4cplus:ERROR Please initialize the log4cplus system properly.
> 2020-04-22 15:38:12 INFO    genericpipeline: Beginning step createmap_cal
> 2020-04-22 15:38:12 ERROR   genericpipeline: *******************************************
> 2020-04-22 15:38:12 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Calibrator
> 2020-04-22 15:38:12 ERROR   genericpipeline: Detailed exception information:
> 2020-04-22 15:38:12 ERROR   genericpipeline: <class 'ModuleNotFoundError'>
> 2020-04-22 15:38:12 ERROR   genericpipeline: No module named 'PipelineStep_createMapfile'
> 2020-04-22 15:38:12 ERROR   genericpipeline: No module named 'PipelineStep_createMapfile'
> Traceback (most recent call last):
>   File "/opt/lofar/lib/python3.6/site-packages/lofarpipe/support/control.py", line 155, in go
>     self.pipeline_logic()
>   File "/opt/lofar/bin/genericpipeline.py", line 366, in pipeline_logic
>     **inputdict)
>   File "/opt/lofar/bin/loader.py", line 13, in call_plugin
>     plugin = load_plugin(path, name)
>   File "/opt/lofar/bin/loader.py", line 8, in load_plugin
>     mod = __import__("PipelineStep_" + name)
> ModuleNotFoundError: No module named 'PipelineStep_createMapfile'
> 2020-04-22 15:38:12 ERROR   genericpipeline:
>   File "/opt/lofar/lib/python3.6/site-packages/lofarpipe/support/control.py", line 155, in go
>     self.pipeline_logic()
>    File "/opt/lofar/bin/genericpipeline.py", line 366, in pipeline_logic
>     **inputdict)
>    File "/opt/lofar/bin/loader.py", line 13, in call_plugin
>     plugin = load_plugin(path, name)
>    File "/opt/lofar/bin/loader.py", line 8, in load_plugin
>     mod = __import__("PipelineStep_" + name)

This is what I got earlier on the other machine, so it seems the fix is working?

Anyway, I noticed that there are no LoSoTo, RMExtract and LSMTool in those (base, pipeline) Dockerfiles. So no wonder that Prefactor is not working and actuall it not proves that Prefactor master is still not compatibile with LOFARsoft 4.x and Python 3
