### ISSUE TITLE
'MSColumns' does not name a type; did you mean 'ROMSColumns'

### ISSUE THREAD

**Issue by o-smirnov** [casacore/python-casacore#204]
Getting a build error when building meqtrees with 3.3, but it looks like a purely casacore issue.

https://github.com/ska-sa/meqtrees-timba/issues/58

```
In file included from /src/casarest/msvis/MSVis/CalVisBuffer.h:32:0,
                 from /src/casarest/msvis/MSVis/CalVisBuffer.cc:28:
/src/casarest/msvis/MSVis/VisBuffer.h:644:19: error: 'MSColumns' does not name a type; did you mean 'ROMSColumns'?
     virtual const MSColumns & msColumns() const {
                   ^~~~~~~~~
                   ROMSColumns
```

**Comment by gervandiepen** [comment]
All ROMS classes have been removed (integrated in the MS ones).
AFAIK casarest has been changed accordingly. Did you renew it?

**Comment by o-smirnov** [comment]
@bennahugo, could you please check the build accordingly? Is casarest updated?

**Comment by gijzelaerr** [comment]
@bennahugo i think this issue can be closed?

**Comment by bennahugo** [comment]
Yes all of this has since been fixed within Meqtrees. Meqtrees-timba builds against cc 3.3.0 and casarest v1.7.0
