### ISSUE TITLE
`python-casacore==3.5` does not work with `numpy==1.22`

### ISSUE THREAD

**Issue by JSKenyon** [casacore/python-casacore#235]
The recent release of version `3.5` makes `python-casacore` compatible with Python 3.10. However, the `numpy` version used to build the wheels is very new (`>=1.23.0`). This is problematic as not all packages (e.g. `numba`) have support for this version of `numpy` which makes installing `python-casacore` under Python 3.10 problematic. Would it be possible to instead build the wheels using `numpy==1.22.x`, the first version of `numpy` to have Python 3.10 support?

**Comment by tammojan** [comment]
Fixed by #236, re-released, and pushed to pip. Could you try to upgrade?

**Comment by JSKenyon** [comment]
I have triggered my 3.10 CI and will let you know if the problem has been resolved ASAP.

**Comment by JSKenyon** [comment]
Thanks @tammojan! My 3.10 CI is working as expected. :-)
