### ISSUE TITLE
Source distribution for 3.5.2

### ISSUE THREAD

**Issue by rtobar** [casacore/python-casacore#240]
Hi,
I just found today that there's no source distribution for python-casacore 3.5.2 in PyPI. Could one please be added? It will allow building python-cascacore in those platforms/python versions for which there's no binary wheel published yet. Thanks!

**Comment by tammojan** [comment]
Oops, 3.5.2 wasn't even tagged as a release here. The source code is identical to 3.5.0 and 3.5.1 but I can see that it's clearer to have the source distribution version in sync with the binary wheel version. I tagged 3.5.2 and uploaded a source distribution to pypi.

**Comment by rtobar** [comment]
Thanks @tammojan!
