### ISSUE TITLE
Binary wheels for python 3.11

### ISSUE THREAD

**Issue by rtobar** [casacore/python-casacore#244]
Hi,

In one of the packages we use in SKA we have a dependency on python-casacore. We are currently using python 3.10, but a quick experiment with 3.11 confirmed that the performance benefits it brings apply to our code.

From all our dependencies, python-casacore is the only one that doesn't provide a 3.11 binary wheel. Could this be catered for? If we were given some general guidelines or preferences on the generation method for these wheels (cibuildwheel, manual docker+script approach, preferred casacore version, etc) we could even provide a PR in this repo to automate wheel generation on CI, after which someone else could publish them (alternatively we could also automate the publishing as well).

**Comment by tammojan** [comment]
Uploaded to pipy now.

**Comment by rtobar** [comment]
Thanks @tammojan, working like a charm :)
