### ISSUE TITLE
setup.py doesn't detect changes in casacore

### ISSUE THREAD

**Issue by gmloose** [casacore/python-casacore#25]
The interface of one of the functions in libcasa_casa had changed (from 'casa::ArrayBase::baseReform(casa::ArrayBase&, casa::IPosition const&) const' to 
'casa::ArrayBase::baseReform(casa::ArrayBase&, casa::IPosition const&, bool) const'), but setup.py did not force a recompile of the sources using this changed file; it bluntly copied the so-files from the cache ('build/lib.linux-x86_64-2.7') into the install directory. As a result I got the following error when trying to import a pyrap module:

$ python -c 'import pyrap.tables'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyrap/tables.py", line 1, in <module>
    from casacore.tables import *
  File "casacore/tables/__init__.py", line 60, in <module>
    from table import table
  File "casacore/tables/table.py", line 44, in <module>
    from _tables import Table
ImportError: casacore/tables/_tables.so: undefined symbol: _ZNK4casa9ArrayBase10baseReformERS0_RKNS_9IPositionE

The workaround is to ditch the build directory every time, but that's a bit of a pity, because most of the time a recompile is not needed.

**Comment by gijzelaerr** [comment]
I think this is not easy to solve (or if you think it is please let me know), we should be more stricter about version checking and stabilising the ABI.

**Comment by gmloose** [comment]
On 31/08/15 17:14, Gijs Molenaar wrote:
>
> I think this is not easy to solve (or if you think it is please let me
> know), we should be more stricter about version checking and
> stabilising the ABI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/python-casacore/issues/25#issuecomment-136402714>.
>
Hi Gijs,

Why not. If the installed casacore headers and libraries are newer than
the ones in the python-casacore build cache, then a rebuild should be
triggered. Shouldn't be too hard, or am I overlooking something here?

Cheers,
Marcel.

**Comment by gijzelaerr** [comment]
I have no idea how to configure setuptools this way, if you know how to and it is trivial please issue a pull request.

**Comment by gmloose** [comment]
Well, I'm not a setuptools expert. It seems that distutils has some support for dependency tracking (http://docs.python.org/2/distutils/apiref.html#module-distutils.dep_util), but I have no idea how you'd have to add this to setup.py

**Comment by alxames** [comment]
This just bit me too.

**Comment by tammojan** [comment]
A trick found in https://github.com/qsnake/scipy/blob/master/src/scipy/lib/blas/setup.py is to create a dummy source file if an external file has changed. But I don't know how to find the absolute path of the casacore includes from setup.py...
