### ISSUE TITLE
pip install can't find proper boost directory

### ISSUE THREAD

**Issue by peijin94** [casacore/python-casacore#252]
On MacOS 14.1.1 M2
the installation command ``` python -m pip install python-casacore``` returns error message of:

```
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/peijinz/lofarsun/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/fit.cc -o build/temp.macosx-14-arm64-cpython-311/src/fit.o -std=c++11
      src/fit.cc:28:10: fatal error: 'boost/python.hpp' file not found
      #include <boost/python.hpp>
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

Have installed boost with ```brew install boost```
Tried ```--no-binary``` option, still getting the same error

**Comment by gmloose** [comment]
The current `setup.py` is a bit "stupid" and quite Linux-oriented (rework is planned). You may want to set the environment variable `LD_LIBRARY_PATH` to the path containing the Boost libraries. That should help finding the right libs.

**Comment by ludwigschwardt** [comment]
Hi, I fixed this a while ago in my `cibuildwheel` branch, but never committed the code 😅 I've made a PR. Peijin, could you check if it works for you?

**Comment by peijin94** [comment]
I can confirm I have the directory /opt/homebrew/include/boost/
But still, it shows the can't find boost/python.hpp error.
Should I set `-L -I` manually before `pip install`

**Comment by tammojan** [comment]
You could have a look at the setup.py, where it specifies the include path and library path, and hack in your local directories there.

**Comment by peijin94** [comment]
`python setup.py` in the newest master branch commit.

Still have boost/python.hpp not found error.
Strange that it doesn't show the "boost not installed error"
