### ISSUE TITLE
Test python3 in travis

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#32]
As mentioned by @brentjens in #31, we should test python3 in travis. This needs python3 functionality in `libcasacore2-dev` package in `ppa:radio-astro/main`. I'm not sure that is the case yet, since the python3 stuff is currently only in casacore master.

**Comment by gijzelaerr** [comment]
this is not the case yet, we need to first make a release.

**Comment by brentjens** [comment]
Before a casacore release is made, it would help to ensure that no python2 boost libraries are linked with the casa_python3 lib when also building the casa_python lib. I found that if I do *not* build the casa_python lib, the cas_python3 lib is only linked with boost_python3, so then all is fine.

Current situation:
-DBUILD_PYTHON=YES  -DBUILD_PYTHON3=YES : boost_python AND boost_python3 linked to casa_python3 -> trouble down the road

-DBUILD_PYTHON=NO  -DBUILD_PYTHON3=YES : only boost_python3 linked to casa_python3 -> All is fine when used with  Python3.

**Comment by tammojan** [comment]
@gijzelaerr is currently working on better python3 support, probably fixing this as well. To be continued later today.

**Comment by brentjens** [comment]
Great!

**Comment by gijzelaerr** [comment]
@brentjens can you verify this PR solves your problem?

https://github.com/casacore/casacore/pull/280

**Comment by brentjens** [comment]
On 18-12-15 12:53, Gijs Molenaar wrote:
> @brentjens <https://github.com/brentjens> can you verify this PR solves your problem?
>
> casacore/casacore#280 <https://github.com/casacore/casacore/pull/280>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/python-casacore/issues/32#issuecomment-165761577>.
>

brentjens@brentjenslaptop:~/abs/casacore.git/build (git python3-fix)  - - - - - - - - - - - - - - - - - - - - - - - - - 
[13:23:09]
$ cmake -DUSE_FFTW3=ON -DDATA_DIR=$HOME/Software/casa-measures/data -DUSE_OPENMP=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON 
-DBUILD_PYTHON3=ON -DUSE_THREADS=ON -DBoost_NO_BOOST_CMAKE=True   ../

brentjens@brentjenslaptop:~/abs/casacore.git/build (git python3-fix)  - - - - - - - - - - - - - - - - - - - - - - - - - 
[13:45:48]
$ ldd python3/libcasa_python3.so|grep boost
         libboost_python3.so.1.59.0 => /usr/lib/libboost_python3.so.1.59.0 (0x00007f02d3484000)

Looks good....

brentjens@brentjenslaptop:~/abs/casacore.git/build (git python3-fix)  - - - - - - - - - - - - - - - - - - - - - - - - - 
[13:46:00]
$ ldd python/libcasa_python.so|grep boost
         libboost_python.so.1.59.0 => /usr/lib/libboost_python.so.1.59.0 (0x00007ff7a77ff000)

Looks good too...


$ ipython
Python 3.5.1 (default, Dec  7 2015, 12:58:09)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import casacore.tables as tab

In [2]:


Everything works! Thanks.

- Michiel

**Comment by gijzelaerr** [comment]
we now test for python3.4 on ubuntu https://github.com/casacore/python-casacore/commit/52a45c119cce226f90a616c39174a56be52cb171
