### ISSUE TITLE
Build within anaconda on OSX 10.11

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#34]
I solved this issue, but will record it here in the hope that it will save someone else the hours that I wasted on it.
I wanted to run python-casacore within an ipython on OSX, and chose to use Anaconda for ipython (instead of for example brew). Anaconda is a flexible system for switching python environments.

To install python-casacore in a conda package, I used (with a lot of stuff that is only necessary because I installed casacore in a non-standard location):
```
pip install ~/opt/python-casacore/src/ --global-option=build_ext --global-option="-L/Users/dijkema/opt/casacore//lib" --global-option="-I/Users/dijkema/opt/casacore/include:/Users/dijkema/anaconda/envs/itaql/include/python2.7" --global-option="-R/Users/dijkema/opt/casacore/lib"
```
This failed on an error
```
error: no template named 'shared_ptr' in namespace 'std'
```
while funnily the same command from outside the conda environment did succeed.

The solution was to explicitly use `libc++`:
```
CFLAGS="-stdlib=libc++ -mmacosx-version-min=10.8" LINKFLAGS="-mmacosx-version-min=10.8 -stdlib=c++" pip install ~/opt/python-casacore/src/ --global-option=build_ext --global-option="-L/Users/dijkema/opt/casacore//lib" --global-option="-I/Users/dijkema/opt/casacore/include:/Users/dijkema/anaconda/envs/itaql/include/python2.7" --global-option="-R/Users/dijkema/opt/casacore/lib"
```

**Comment by tammojan** [comment]
The solution came from Juanlu001/fenics-recipes#16

**Comment by gijzelaerr** [comment]
maybe we should try to make a anaconda package for casacore and python-casacore. I I already tried, but got distracted by other things. If I remember correctly it took days before their buildfarm started building the packages. Also it wasn't clear to me how to properly manage dependencies.

https://anaconda.org/gijzelaerr/casacore

**Comment by bhazelton** [comment]
I just stumbled across this while trying to get casacore-python to work for me. There is a conda-forge package for casacore (https://anaconda.org/conda-forge/casacore). I haven't yet been able to get the pip installed casacore-python to work with the conda-forge casacore package, but I'll try something along the lines of what tammojan did.

**Comment by tammojan** [comment]
See also casacore/casacore#596

**Comment by bhazelton** [comment]
Just to follow up on this, my collaborator, Peter Williams, just made a python-casacore conda-forge package that seems to work beautifully. It's available at https://anaconda.org/conda-forge/python-casacore.

**Comment by tammojan** [comment]
Thanks for letting us know, this looks very promising. I tested it on MacOS and it works like a charm.
