### ISSUE TITLE
from casacore import tables problem

### ISSUE THREAD

**Issue by HannoSpreeuw** [casacore/python-casacore#35]
I did two installs, on Ubuntu 14.04.2 LTS - VirtualBox guest, with sudo apt-get install python-casacore etc. - and on Fedora 22, using casacore-2.0.3 and python-casacore-2.1.0:
as user I did:
python setup.py build_ext -I/usr/local/include/casacore/ -I/usr/include/cfitsio
and as root:
python setup.py install

However, the Fedora install showed problems at a later stage:
[hspreeuw@localhost ~]$ python
Python 2.7.10 (default, Sep 24 2015, 17:50:09) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import casacore as casac
>>> from casacore import tables as tbls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/python_casacore-2.1.0-py2.7-linux-x86_64.egg/casacore/tables/__init__.py", line 60, in <module>
    from table import table
  File "/usr/lib64/python2.7/site-packages/python_casacore-2.1.0-py2.7-linux-x86_64.egg/casacore/tables/table.py", line 44, in <module>
    from _tables import Table
ImportError: libcasa_tables.so.2: cannot open shared object file: No such file or directory

What I did is to compare the contents fo the tables directory on Fedora and the Ubuntu VirtualBox guest to try to solve the problem, but I am not sure if I can conclude anything.
Anyway, on Ubuntu:
ls /usr/lib/python2.7/dist-packages/casacore/tables/
__init__.py   msutil.py   tablecolumn.py   tablehelper.py   tableindex.py   tableiter.py   table.py   tablerow.py   _tables.so    tableutil.pyc      wxtablebrowser.pyc
__init__.pyc  msutil.pyc  tablecolumn.pyc  tablehelper.pyc  tableindex.pyc  tableiter.pyc  table.pyc  tablerow.pyc  tableutil.py  wxtablebrowser.py

On Fedora:
ls /usr/lib64/python2.7/site-packages/python_casacore-2.1.0-py2.7-linux-x86_64.egg/casacore/tables/
__init__.py   msutil.py   tablecolumn.py   tablehelper.py   tableindex.py   tableiter.py   table.py   tablerow.py   _tables.py   _tables.so    tableutil.pyc      wxtablebrowser.pyc
__init__.pyc  msutil.pyc  tablecolumn.pyc  tablehelper.pyc  tableindex.pyc  tableiter.pyc  table.pyc  tablerow.pyc  _tables.pyc  tableutil.py  wxtablebrowser.py

On Fedora, there are two extra files, _tables.py (underscoretables.py) and _tables.pyc (underscoretables.pyc), which are not made in the Ubuntu install. 
This is _tables.py:
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, imp
    __file__ = pkg_resources.resource_filename(__name__, '_tables.so')
    __loader__ = None; del __bootstrap__, __loader__
    imp.load_dynamic(__name__,__file__)
__bootstrap__()

I guess this is probably not the cause of the problem, but I wanted to mention it.

There is a similar problem when importing the images module and possibly also when importing other casacore modules.

What is an elegant way to fix this?

**Comment by tammojan** [comment]
The `libcasa_tables.so.2` is a file that should be installed when installing casacore. How and where did you install install casacore? If you can find the file manually (perhaps in `/usr/local/lib` or some other library directory) you can add that path to your $LD_LIBRARY_PATH before running python.

If this works, you can also recompile python-casacore with an rpath, but first let's try to find the file.

**Comment by HannoSpreeuw** [comment]
This file is in /usr/local/lib.
python setup.py build_ext --force -I/usr/local/include/casacore/ -I/usr/include/cfitsio -R/usr/local/lib
worked, thanks!
