### ISSUE TITLE
RuntimeError: Table DataManager error: Data Manager class LofarStMan is not registered

### ISSUE THREAD

**Issue by HannoSpreeuw** [casacore/python-casacore#36]
This occurs with both my python-casacore installs, a Fedora 22 "manual" install - using casacore-2.0.3 and python-casacore-2.1.0 - and an Ubuntu 14.04 automatic install.

[hspreeuw@localhost MS]$ python -c "import casacore.tables as pt; t = pt.table('L64371_SAP000_SB000_uv.MS')"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/python_casacore-2.1.0-py2.7-linux-x86_64.egg/casacore/tables/table.py", line 311, in __init__
    Table.__init__ (self, tabname, lockopt, opt);
RuntimeError: Table DataManager error: Data Manager class LofarStMan is not registered

**Comment by tammojan** [comment]
LofarStMan is part of the Lofar software, you should install it separately.

**Comment by tammojan** [comment]
For an idea on installing the LOFAR software, have a look at e.g. https://github.com/lofar-astron/lofar-deploy/blob/master/src/common/install-lofar.sh . To install only LofarStMan, use `-DBUILD_PACKAGES=LofarStMan` at CMake time (so you don't need a lot of the dependencies).

**Comment by HannoSpreeuw** [comment]
Thanks, I'll try. The problem is that googling this error message gets you here:
ftp://ftp.strw.leidenuniv.nl/pub/tasse/lofar_imaging_cookbook_v11.pdf
It says:
Troubleshooting
. If you receive the following error then probably the daily build is broken and you should revert to a previous build with "use LofIm <day>".

That pointed me in the wrong direction.

**Comment by tammojan** [comment]
Ah yes, we should probably put in the cookbook that that is specific to an installation on our cluster. Although changing it in the cookbook will not fix the out of date release on that page...

**Comment by HannoSpreeuw** [comment]
I installed LofarStMan, somewhat following the instructions here 
http://www.lofar.org/operations/doku.php?id=public:user_software:ubuntu_14_4
under "Download and Build the LOFAR Software":
/opt/soft/lofar-stuff/BuildDir/lofarsoft/build/gnu_opt$ sudo cmake -DBUILD_TESTING=NO -DBUILD_SHARED_LIBS=ON -DUSE_OPENMP=ON -DBUILD_PACKAGES="LofarStMan" -DCMAKE_INSTALL_PREFIX:PATH=/opt/soft/lofar-stuff   ../../LOFAR/

The error remains, but should I change $LD_LIBRARY_PATH before running Python? To what?

**Comment by tammojan** [comment]
I think including /opt/soft/lofar-stuff/lib in your LD_LIBRARY path should do the trick.

**Comment by HannoSpreeuw** [comment]
Thanks, fixed for my Ubuntu 14.04 VirtualBox guest.
sudo apt-get install lofar
export LD_LIBRARY_PATH=/usr/lib64
python -c "import casacore.tables as pt; t = pt.table('L64371_SAP000_SB000_uv.MS')"
----->
Successful readonly open of default-locked table L64371_SAP000_SB000_uv.MS: 23 columns, 158841 rows

**Comment by tammojan** [comment]
Great. And, as a bonus, you get the lofar applications, like DPPP :)
