### ISSUE TITLE
Probable bug: Zero-valued DATA for large MS depending on how you read

### ISSUE THREAD

**Issue by cyriltasse** [casacore/python-casacore#38]
With python-casacore 2.1.0 (see bellow for the linking)

Description: The data read at once gives a numpy array that has zeros values after a certain row. That does not happen if the data is not read at once (so it's not the data that contains zeros). This is done on a system with 256Gb of RAM, so that's enough to host the full data array.

`
# get the full data as an array

d=t.getcol("DATA")
print d.shape

> (27203365, 64, 4)
# select subsample from full array and directly from disc

incr=2179
dsel_FromArray=d[1::incr,10,0]
dsel_FromDisk=t.getcol("DATA",1,rowincr=incr)[:,10,0]
# Plot

pylab.plot(dsel_FromDisk.real)
pylab.plot(dsel_FromArray.real)
pylab.legend(("From sliced file on disk","From sliced Array"))
pylab.xlabel("Bin number")
pylab.ylabel("Real part of visibility")
pylab.show()
`

![figure_1 6](https://cloud.githubusercontent.com/assets/6523227/12778457/0e8715cc-ca63-11e5-8a94-7d0ef90099f4.png)

ldd /cep/lofar/python-casacore/lib/python2.7/site-packages/casacore/tables/_tables.so
    linux-vdso.so.1 =>  (0x00007ffe4e7c1000)
    libcasa_tables.so.2 => /cep/lofar/casacore/lib/libcasa_tables.so.2 (0x00007fefae12c000)
    libboost_python-py27.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0 (0x00007fefadedf000)
    libcasa_python.so.2 => /cep/lofar/casacore/lib/libcasa_python.so.2 (0x00007fefadbfc000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fefad8f8000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fefad6e2000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fefad31d000)
    libcasa_casa.so.2 => /cep/lofar/casacore/lib/libcasa_casa.so.2 (0x00007fefacdad000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fefacb8f000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fefac889000)
    libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fefac67a000)
    libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fefac116000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fefaed13000)
    libhdf5.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5.so.7 (0x00007fefabc7a000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fefaba76000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fefab85d000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fefab65a000)

**Comment by tammojan** [comment]
Thanks for the detailed report. I have tried to reproduce this (also with a large dataset, 5.6G), but the two methods yield the same result for me. Could it be that you ran out of memory?

**Comment by cyriltasse** [comment]
@tammojan thanks for the quick answer. The dataset is bigger (190Gb - DATA+CORRECTED_DATA), basically an uncompressed single LOFAR LBA subband (64 channels / 1s bin, 7 hours integration). The system has 256 Gb RAM, so enough to host the array.

**Comment by cyriltasse** [comment]
To be sure it wasn't connected to a type problem, I've tested replacing the raw data values which have levels between 10^6 and 10^8 by ones. Same behaviour...

**Comment by tammojan** [comment]
Can you reproduce it with a smaller array (say half of your data), to make sure that it's not a memory problem?

**Comment by cyriltasse** [comment]
# On a smaller MS
I've cut the MS to 42% of its original size and now I get a perfect match! But does that mean this is a memory problem? I'm not completely convinced.

![figure_1](https://cloud.githubusercontent.com/assets/6523227/12779792/eaf841fe-ca61-11e5-9046-8aa3b6e28397.png)

# On the original MS
During loading the DATA array, the memory consumption peaks at 82 Gb (out of 256 Gb)

**Comment by cyriltasse** [comment]
# Original MS
d=t.getcol("DATA")

This is the memory consumption as a function of time (green is allocated to the process, gray is cache). It seems to have a plateau.

![figure_1](https://cloud.githubusercontent.com/assets/6523227/12780027/7bc5b904-ca63-11e5-9921-5166c1491d0b.png)

**Comment by tammojan** [comment]
I think that numpy requires contiguous memory, so even if you have enough memory available, it may not be contiguous. I agree that giving zeroes in case of (possibly) memory problems isn't desirable. Some kind of other error would be more acceptable.

Until this is solved, you just convinced yourself that using slicing from disk is safer for arrays larger than say 50Gb.

**Comment by cyriltasse** [comment]
# On the smaller MS where no missbehaviour is observed
![figure_1](https://cloud.githubusercontent.com/assets/6523227/12780142/ff152e70-ca63-11e5-849a-eb05e4c4abce.png)

**Comment by cyriltasse** [comment]
Somehow part of the allocated array gets deallocated. See the difference between the two previous plots at the end of the read. How can that be?

**Comment by tammojan** [comment]
Perhaps the deallocation happens at the end of the program, which may be negligible in the 'small' example?

**Comment by cyriltasse** [comment]
My eye sees that the dip behind the bump at 2 and 1 min. *does* and *does not* happen respectively.

**Comment by cyriltasse** [comment]
... and that the size of the dip that *does happen* in the first case corresponds to the quantity of zero (missing then) data in the first case...

**Comment by tammojan** [comment]
Agreed. I'll have to ask @gervandiepen to comment on that. Thanks for your detailed report, and I hope you have enough input to at least continue your work (using the slicer from disk).

**Comment by cyriltasse** [comment]
@tammojan Thanks for looking at that issue. It's actually quite blocking for me. I'd need to modify the architecture of my software to use data chunks compatible with what casacore can or cannot do which is a bit unclear now. I'd prefer a bug fix of course if possible.

**Comment by cyriltasse** [comment]
Any news from @gervandiepen ?

**Comment by gervandiepen** [comment]
Hi Cyril,

I've taken a look, but cannot pinpoint the problem.
The coming weeks I have little time because I have to finish SDP documents
and have a week leave.

I'll take a look again after March 5th.
Ger

**Comment by cyriltasse** [comment]
Hey Ger,

Thanks very much, I think you're the only person in the observable universe that can have an idea on that weird thing. CountedPointer or so? Can you reproduce? If not let me know,

Cyril

**Comment by tammojan** [comment]
Hi @cyriltasse ,

Perhaps, as a workaround, you could try something like:

```
# Allocate full array
fulldata=t.getcol("DATA",0,1)
fulldata.resize((t.nrows(),dsel_FromDisk.shape[1],dsel_FromDisk.shape[2]))

incr=2179
current_row=0

# Fill the array in chunks
for current_row in range(0, t.nrows(), incr):
  fulldata[current_row:current_row+incr]=t.getcol("DATA",current_row,incr)

dsel_FromArray=fulldata[1::incr,10,0]
```

This shouldn't affect how you work with your data too much does it? 

I'm not sure this works, because the array `fulldata` will again be very large, maybe too large. But if it is, this piece of code could help show whether the error is at the numpy side or at the casacore side.

**Comment by cyriltasse** [comment]
@tammojan yep something like that should probably be all right. I'll try when that gets critical again. Although probably not very efficient in terms of I/O... But thanks for thinking of it!

**Comment by tammojan** [comment]
@cyriltasse I updated the code a bit, even in these 7 lines I made a mistake.. You can make the I/O more efficient by setting `chunksize` very large (at the extreme to something as large as the whole MS, but then I'm pretty sure you'll see zeros again).

**Comment by tammojan** [comment]
Hi @cyriltasse ,

You're probably looking for the following function (thanks @gervandiepen ):

```
    def getcolnp (self, columnname, nparray, startrow=0, nrow=-1, rowincr=1):
        """Get the contents of a column or part of it into the given numpy array.
        The numpy array has to be C-contiguous with a shape matching the
        shape of the column (part). Data type coercion will be done as needed.
        If the column contains arrays, they should all have the same shape.
        An exception is thrown if they differ in shape. In that case the
        method :func:`getvarcol` should be used instead.
        The column can be sliced by giving a start row (default 0), number of
        rows (default all), and row stride (default 1).
        """
        if not nparray.flags.c_contiguous  or  nparray.size == 0:
            raise ValueError("Argument 'nparray' has to be a contiguous numpy array")
        return self._getcolvh (columnname, startrow, nrow, rowincr, nparray)
```

**Comment by cyriltasse** [comment]
Ho nice I'll have a look!

**Comment by tammojan** [comment]
The docs on readthedocs weren't updated properly, so I moved them to github instead. The documentation for `getcolnp` is now at
http://casacore.github.io/python-casacore/casacore_tables.html#casacore.tables.table.getcolnp
(in case you had troubles with the markdown...)
