### ISSUE TITLE
Docs on readthedocs are wrong

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#40]
The docs on readthedocs only contain the static `.rst` files, not the auto generated documentation. @gijzelaerr , how do I access the settings on readthedocs? Are you the owner of this project?

**Comment by tammojan** [comment]
Never mind, I have admin access to the readthedocs repo now. It tries to install python-casacore and fails to find boost-python. From the logs:

```
install
-----

src/fit.cc:28:28: fatal error: boost/python.hpp: No such file or directory
 #include <boost/python.hpp>
                            ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I'll see if I can fix this easily (it shouldn't need to build python-casacore in order to make the docs).

**Comment by tammojan** [comment]
Hm actually @gijzelaerr it seems you're the only one with admin access to the python-casacore readthedocs page. Can you add me?

**Comment by gijzelaerr** [comment]
this is sort of a duplicate of

https://github.com/casacore/python-casacore/issues/14

**Comment by tammojan** [comment]
> this is sort of a duplicate of #14

Agreed. I hadn't realized that #14 means that the documentation is not built (not the useful part).

**Comment by tammojan** [comment]
Duplicate of #14
