### ISSUE TITLE
Opening a list of subtables with :: notation does not work

### ISSUE THREAD

**Issue by sabourke** [casacore/python-casacore#47]
Specifying a list of subtables with :: notation for concatenation does not work.
Eg:
vtab = table(["a.ms::ANTENNA", "b.ms::ANTENNA"])
does not work.

vtab = table(["a.ms/ANTENNA", "b.ms/ANTENNA"])
works fine.

**Comment by gervandiepen** [comment]
This basically a problem in Casacore's TableProxy.cc, for which I'll file an issue (and fix it).

**Comment by gijzelaerr** [comment]
this issue has been resolved in casacore and is release in 2.1.0
