### ISSUE TITLE
tables.tablecopy() ignores many of its arguments

### ISSUE THREAD

**Issue by sabourke** [casacore/python-casacore#48]
tablecopy doesn't pass dminfo, endian, memorytable, copynorows in its call to table.copy()

**Comment by gervandiepen** [comment]
What exactly did you try?

I tried
   t3=t2.copy('c.ms
',dminfo={'a':{'COLUMNS':['TIME'],'TYPE':'StandardStMan','NAME':'tmp'}})
which worked well.

I looked at the code and it looks fine. However, I noticed in TableProxy.cc
that if only copynorows=True is given, it is not taken into account. I'll
fix that.

**Comment by gervandiepen** [comment]
I was mistaken. copynorows is taken into account by TableProxy.cc.

But now I understand.
The culprit is tablecopy in tableutil.py, not table.copy. I'll fix it.

Ger
