### ISSUE TITLE
pyrap images crashes when image data is float64

### ISSUE THREAD

**Issue by SpheMakh** [casacore/python-casacore#57]
I get this error when the image data is float64
```
RuntimeError: The lattice does not appear to be an image
```
It goes away after after I typecast the data as float32

**Comment by gervandiepen** [comment]
I assume you have used a FITS file as input.
Casacore issue github.com/casacore/casacore/issues/292 has solved this issue, but is not available in python until a new release of casacore.python is done.

**Comment by tammojan** [comment]
We released python-casacore 2.1.3 this afternoon.

**Comment by gijzelaerr** [comment]
@gervandiepen if it was solved in casacore why do you need a new release for python-casacore?

**Comment by SpheMakh** [comment]
I'm closing this since it's a duplicate.

**Comment by gijzelaerr** [comment]
duplicate of what?

**Comment by SpheMakh** [comment]
Its the same issue as github.com/casacore/casacore/issues/292

**Comment by gervandiepen** [comment]
You're right. Building (against) a new casacore is sufficient.
