### ISSUE TITLE
Add some more tests to have at least 70% coverage

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/python-casacore#6]

**Comment by anchitjain1234** [comment]
1. Added tests for gaussian1d

**Comment by mohanagr** [comment]
Hello! I'd like to contribute more to the testing and coverage part of this project. I have decent python3 experience and have done some testing. 
Shouldn't we refactor the tests with `pytest`? it's much more extensive and flexible.

**Comment by tammojan** [comment]
Moving to `pytest` is definitely an option. Is that also capable of running the c++-tests?

**Comment by tammojan** [comment]
> Also, is there an irc channel/gitter/slack where I can connect?

You're welcome at gitter: https://gitter.im/casacore/python-casacore

**Comment by gijzelaerr** [comment]
lets just close this issue, i think we have a good enough test suite now.
