### ISSUE TITLE
Expose MeasurementSet functionality

### ISSUE THREAD

**Issue by sjperkins** [casacore/python-casacore#61]
It would be helpful if requiredTableDesc was exposed in the python wrappers so that access to the basic table configuration was available for creating new tables.

Had a quick go at adding it in pytables.cc but requiredTableDesc doesn't live on TableProxy (looks like its a static method on MeasurementSet).

**Comment by gervandiepen** [comment]
pytables and TableProxy form a generic casacore table interface, while
requiredTableDesc is a MeasurementSet-specific function. However, I can see
it is useful. I'll think about it. Maybe a python interface to MS
functionality is needed.

**Comment by sjperkins** [comment]
Hypothetically speaking, would such an interface also have access to methods such as `createDefaultSubtables`?

**Comment by gervandiepen** [comment]
Yes, it would.

**Comment by brentjens** [comment]
Exposing the MS functionality would help greatly in e.g. writing an MS filler for LOFAR station visibility data too.

**Comment by gijzelaerr** [comment]
this has been implemented in this PR https://github.com/casacore/python-casacore/pull/72
