### ISSUE TITLE
Update Pypi with new README.rst

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/python-casacore#62]
since it looks like 💩 at the moment on pypi

https://pypi.python.org/pypi/python-casacore/2.1.2

**Comment by shibasisp** [comment]
How this can be done? I think it's already written in rst.

**Comment by tammojan** [comment]
It is indeed currently already in RST. I changed the ticket name to reflect that somehow we need to update pip.

**Comment by shibasisp** [comment]
Looks like there was a small indentation error in the README.rst, because of which PyPI wasn't able to render the rST into HTML. I have pushed a commit to my fork. But I don't know how can I modify the README.rst of tag v2.1.2

**Comment by tammojan** [comment]
You cannot change anything in a tag, because it has been released. We should look at releasing another version soon. Or create a test tag just for this.

**Comment by shibasisp** [comment]
should I send a PR so that it will render correctly in the next release?

**Comment by tammojan** [comment]
Yes please.
