### ISSUE TITLE
python-casacore ephemeris information

### ISSUE THREAD

**Issue by AntoniaR** [casacore/python-casacore#70]
How can I identify which ephemeris data python-casacore uses, how can I force it to use a specific version and how can I update it? This information is not covered in the python-casacore documentation.

Basically, I am having an issue with the ephemeris being out of date in casacore and I am trying to identify if this is because the ephemeris data needs updating or if the update is not working. See issue here: https://github.com/transientskp/tkp/issues/542

I have installed casacore using the latest measures data from the ftp site following the instructions here: https://github.com/casacore/casacore

I then installed python-casacore using `pip install python-casacore`

I then ran the following code in ipython, after checking it was calling the correct python-casacore. See the instructions here: http://tkp.readthedocs.io/en/latest/getstart/casacore-measures-data.html 
`from casacore.measures import measures
dm = measures()
dm.do_frame(dm.epoch('UTC', '2015/01/01'))
dm.separation(dm.direction('SUN'), dm.direction('SUN'))`
But this still fails because the ephemeris is still out of date. So I want to check if this failure is because python-casacore is not looking at the correct ephemeris or if the ephemeris is out of date.

I have tried this on a virtual machine, but it is possible it is still calling an old version of the ephemeris. Unfortunately, I am having issues on my laptop so not been able to get python-casacore installed correctly.

Thanks!

**Comment by tammojan** [comment]
If you can get into the virtual machine, and the casacore binaries are also installed somewhere, you could call the casacore binary file `findmeastable`. This will print the path of the data table to be used.

To override the system setting of the data path, you can make a file `.casarc` in your home directory, with the line
```
measures.directory: /Users/dijkema/opt/casacore/data
```

Where the data is a directory containing the two subdirectories `geodetic` and `ephemiredes` (as can be obtained from the tarball at the Astron site).

**Comment by AntoniaR** [comment]
Thank you for this! It was really helpful in testing the code. I have the most recent version of the measurements table from ASTRON, then followed your instructions to force casacore to use this data and confirmed it worked using the `findmeastable` command.

Unfortunately this did not solve the problem, therefore I have been able to confirm that the measures data at ASTRON is out of date. Do you know who I contact regarding that?

**Comment by tammojan** [comment]
Please contact softwaresupport@astron.nl
