### ISSUE TITLE
Check version of casacore during install

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#79]
Python-casacore may require some recent version of casacore, as we encountered in #76 and #72.

I think it's fine to enforce such a dependency (otherwise python-casacore will never be able to wrap or use recent functionality in casacore), but we need to check during install (`setup.py`) whether the available casacore is recent enough. I'm not sure how to do this though..

**Comment by sjperkins** [comment]
It looks like the [version](https://github.com/casacore/casacore/blob/f4dc1c36287c766796ce3375cebdfc8af797a388/casa/version.cc) is baked into the shared library?  If so, it is probably possible to uses ctypes (IIRC this is a standard python package) before the call to `setup` to find out the CASA version.

**Comment by tammojan** [comment]
I fixed this in  687be41 . However, the fix required a change in casacore itself, raising the minimum version to a yet unreleased version of casacore. So I won't make a pull request just yet.
