### ISSUE TITLE
build instructions on RHEL6

### ISSUE THREAD

**Issue by caseyjlaw** [casacore/python-casacore#85]
I'd like to use python-casacore at the AOC in Socorro. They support a standard OS of RHEL6, so I'll need to build python-casacore myself.
In my first attempt, I use an include directory for casacore, wcs, fitsio and it builds with setuptools. However, importing measures or quanta gives an error:
```
In [1]: from casacore import measures
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-19baeda6780f> in <module>()
----> 1 from casacore import measures

/home/widar-boot-1/services/diskless_boot/cbe/cbe-master/realfast/soft/python-casacore/casacore/measures/__init__.py in <module>()
     27 __all__ = ['is_measure', 'measures']
     28 
---> 29 from ._measures import measures as _measures
     30 
     31 import casacore.quanta as dq

ImportError: No module named _measures
```

Are you aware of anyone building this at the AOC or on RHEL6?

**Comment by tammojan** [comment]
I'm not aware of people using python-casacore in Socorro (although they are of course much welcome to).

You can at least work around the import error by setting your `$LD_LIBRARY_PATH` environment variable to contain the directory with `_measures.so` (etc.).

**Comment by gijzelaerr** [comment]
closing this issue since this seems to be resolved, please reopen if you think otherwise.
