### ISSUE TITLE
Problems with Boost 1.64.0

### ISSUE THREAD

**Issue by tammojan** [casacore/python-casacore#96]
As reported https://github.com/conda-forge/casacore-feedstock/commit/61dfb9fb11d151326c7186ca01427fa2cac47075#commitcomment-22394479 , python-casacore (and casacore?) seems to be affected by this boost bug: https://svn.boost.org/trac10/ticket/12516 

I have not reproduced this yet. A workaround is to use Boost 1.63.0, or to apply a one-line patch to the boost headers: https://github.com/boostorg/serialization/commit/1d86261581230e2dc5d617a9b16287d326f3e229

**Comment by gijzelaerr** [comment]
We can't do much about this from the python-casacore code side. Closing this issue since it is more a packaging issue, please reopen if you think otherwise.
